name: sharenetearn
description: Affiliate network hotspot earning app with MLM rewards and UPI payment integ
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  sdk: flutter
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.0
  cloud_functions: ^4.6.0
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  get_it: ^7.6.0
  http: ^1.1.0
  dio: ^5.3.0
  connectivity_plus: ^5.0.0
  http_certificate_pinning: ^1.1.0
  razorpay_flutter: ^1.3.7
  upi_india: ^2.2.0
  encrypt: ^6.0.0
  flutter_secure_storage: ^9.0.0
  pointycastle: ^3.7.3
  cryptography: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^5.0.0
  flutter_background_service_ios: ^5.0.0
  workmanager: ^0.5.2
  permission_handler: ^11.4.0
  location: ^6.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  lottie: ^2.4.0
  badges: ^3.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  device_info_plus: ^9.1.0
  package_info_plus: ^5.0.0
  uuid: ^4.0.0
  geolocator: ^10.1.0
  logger: ^2.2.0
  sentry_flutter: ^7.10.0
  url_launcher: ^6.2.0
  share_plus: ^7.2.0
  path_provider: ^2.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
